name: 'fastrelease'
description: 'Automatically draft release notes. https://fastrelease.fast.ai/'
inputs:
  TOKEN:
    description: GitHub Token
    require: true
branding:
  color: 'gray-dark'
  icon: 'package'
runs:
  using: 'docker'
  image: 'Dockerfile'
