name: 'fastrelease-publish'
description: 'Publish a release to GitHub.'
inputs:
  token:
    description: GitHub Token
    require: true
runs:
  using: "composite"
  steps: 
    - name: Cut release
      shell: bash
      run: |
        pip install nbdev fastrelease
        fastrelease_release --token "${{ inputs.token }}"
    - name: commit settings.ini
      shell: bash
      run: |
        nbdev_bump_version
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add settings.ini
        git commit -m'[bot] bump version'
        git push
