# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GH_HOST": "00_core.ipynb",
         "run_proc": "00_core.ipynb",
         "do_request": "00_core.ipynb",
         "FastRelease": "00_core.ipynb",
         "fastrelease_changelog": "00_core.ipynb",
         "fastrelease_release": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastrelease.fast.ai/fastrelease/"

git_url = "https://github.com/fastai/fastrelease/tree/master/"

def custom_doc_links(name): return None
