# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GH_HOST": "00_core.ipynb",
         "find_config": "00_core.ipynb",
         "FastRelease": "00_core.ipynb",
         "fastrelease_changelog": "00_core.ipynb",
         "fastrelease_release": "00_core.ipynb",
         "fastrelease": "00_core.ipynb",
         "bump_version": "00_core.ipynb",
         "fastrelease_bump_version": "00_core.ipynb",
         "pypi_json": "01_conda.ipynb",
         "latest_pypi": "01_conda.ipynb",
         "write_pip_conda_meta": "01_conda.ipynb",
         "write_conda_meta": "01_conda.ipynb",
         "fastrelease_conda_package": "01_conda.ipynb"}

modules = ["core.py",
           "conda.py"]

doc_url = "https://fastrelease.fast.ai/"

git_url = "https://github.com/fastai/fastrelease/tree/master/"

def custom_doc_links(name): return None
