name: test-workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Action
      uses: ./action/changelog
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
